/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;
//gerekli kütüphaneler
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author serhat
 */
public class FIYATALMA extends javax.swing.JFrame {

    /**
     * Creates new form FIYATALMA
     */
    public FIYATALMA() {
        initComponents();
        Selectional();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection conn=null;
    Statement stt = null;
    ResultSet rss = null;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        malzemeid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        miktar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ekleme = new javax.swing.JButton();
        çıkarma = new javax.swing.JButton();
        tablostok = new javax.swing.JScrollPane();
        Tablostok = new javax.swing.JTable();
        temizleme = new javax.swing.JButton();
        kar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        güncelleme = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fiyatalma = new javax.swing.JButton();
        anasayfa = new javax.swing.JButton();
        fiyatalma1 = new javax.swing.JButton();
        fiyatalma2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Kapat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        malzemeid.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel10.setText("Malzeme id");

        miktar.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel11.setText("Birim miktari");

        ekleme.setText("EKLE");
        ekleme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eklemeMouseClicked(evt);
            }
        });

        çıkarma.setText("ÇIKAR");
        çıkarma.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                çıkarmaMouseWheelMoved(evt);
            }
        });
        çıkarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                çıkarmaMouseClicked(evt);
            }
        });
        çıkarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çıkarmaActionPerformed(evt);
            }
        });

        Tablostok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MALZEME ID", "MALZEME ADI", "BİRİM CİNSİ", "BİRİM MİKTARI", "BİRİM FİYATI", "KAR ORANI"
            }
        ));
        Tablostok.setRowHeight(30);
        Tablostok.setSelectionBackground(new java.awt.Color(0, 0, 0));
        Tablostok.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Tablostok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablostokMouseClicked(evt);
            }
        });
        tablostok.setViewportView(Tablostok);

        temizleme.setText("CLEAR");
        temizleme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temizlemeMouseClicked(evt);
            }
        });

        kar.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel13.setText("Kar oranı");

        güncelleme.setText("GÜNCELLE");
        güncelleme.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                güncellemeMouseWheelMoved(evt);
            }
        });
        güncelleme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                güncellemeMouseClicked(evt);
            }
        });
        güncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncellemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(malzemeid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(kar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ekleme, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(temizleme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(çıkarma, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tablostok, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(malzemeid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ekleme, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(çıkarma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temizleme, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(güncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(tablostok, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        fiyatalma.setText("FIYAT ALMA");
        fiyatalma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiyatalmaMouseClicked(evt);
            }
        });

        anasayfa.setText("ANA SAYFA");
        anasayfa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anasayfaMouseClicked(evt);
            }
        });

        fiyatalma1.setText("Malzeme sorgu\n");
        fiyatalma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiyatalma1MouseClicked(evt);
            }
        });

        fiyatalma2.setText("Tablo temizleme\n");
        fiyatalma2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiyatalma2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(fiyatalma, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(fiyatalma1)
                .addGap(82, 82, 82)
                .addComponent(anasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(fiyatalma2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyatalma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatalma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatalma2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROKONT FIYAT ALMA\n ");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\serhat\\Pictures\\Ekran görüntüsü 2024-05-24 170938.png")); // NOI18N
        jLabel3.setText("jLabel2");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\serhat\\Pictures\\Ekran görüntüsü 2024-05-24 170938.png")); // NOI18N
        jLabel4.setText("jLabel2");

        Kapat.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Kapat.setForeground(new java.awt.Color(255, 255, 255));
        Kapat.setText("X");
        Kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //veri tabanındaki verileri arayüzdeki tabloya ekleme işlemini yapan fonksiyon
    private void Selectional(){
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
            stt=conn.createStatement();
            rss=stt.executeQuery("select * from yenistok");
            Tablostok.setModel(DbUtils.resultSetToTableModel(rss));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void çıkarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çıkarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_çıkarmaActionPerformed

    private void çıkarmaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_çıkarmaMouseWheelMoved
        
    }//GEN-LAST:event_çıkarmaMouseWheelMoved
//textboxlara girilen verileri silen fonksiyon
    private void temizlemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temizlemeMouseClicked
        malzemeid.setText("");
        miktar.setText("");
        kar.setText("");
    }//GEN-LAST:event_temizlemeMouseClicked
//veri tabanındaki yenistok adlı veri tablosuna veri ekleme işlemi 
    private void eklemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eklemeMouseClicked
        String idText = malzemeid.getText();
        String karOraniText = kar.getText();
        int result=JOptionPane.showConfirmDialog(this, "Eklenmeyi onaylıyormusunuz?");
        if(result==JOptionPane.YES_OPTION){
            if (idText.isEmpty() || karOraniText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen ID ve Kar Oranı girin.", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
            int id = Integer.parseInt(malzemeid.getText());
            Statement işlem = conn.createStatement();
            ResultSet rs = işlem.executeQuery("SELECT * FROM stok where Id="+id);
    
    // Yeni stok tablosuna verileri ekle
    PreparedStatement add = conn.prepareStatement("INSERT INTO yenistok (Id, Ad, Cins, Miktar,kar, Fiyat) VALUES (?, ?, ?, ?, ?,?)");
    
    while (rs.next()) {
        double karOrani = Double.parseDouble(karOraniText) / 100;
        int eskiId = rs.getInt("Id");
        String eskiAd = rs.getString("Ad");
        String eskiCins = rs.getString("Cins");
        
        double eskiFiyat = rs.getDouble("Fiyat");
        eskiFiyat=eskiFiyat+(eskiFiyat*karOrani);
        // Yeni tabloya verileri ekle
        add.setInt(1, eskiId);
        add.setString(2, eskiAd);
        add.setString(3, eskiCins);
        add.setInt(4, Integer.valueOf(miktar.getText()));
        add.setDouble(6, eskiFiyat);
        add.setInt(5, Integer.valueOf(kar.getText()));
        add.executeUpdate();
    }
    
    
            malzemeid.setText("");
            miktar.setText("");
            kar.setText("");
        
            conn.close();
            Selectional();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_eklemeMouseClicked
// yeni stok adındaki veri tablosundaki verilerin hepsinin ücretini hesaplayan ve pdf dosyası oluşturan fonksiyonun kullanıldığı yer
    private void fiyatalmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiyatalmaMouseClicked
               String projectId = malzemeid.getText(); // TextField'den proje ID'sini al
            int result=JOptionPane.showConfirmDialog(this, "pdf dosyasını oluşturmak istiyormusunuz");
   if(result==JOptionPane.YES_OPTION){
        try {
        // Veri tabanından proje bilgilerini al
        
        // Veri tabanından malzeme bilgilerini al
        String[][] materials = getMaterialDetails(projectId);

        if (projectId != null) {
            createPDF( materials);
            JOptionPane.showMessageDialog(null, "PDF başarıyla oluşturuldu!");
        } else {
            JOptionPane.showMessageDialog(null, "Proje ID bulunamadı.");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Hata: " + ex.getMessage());
    }
   }
                
    }//GEN-LAST:event_fiyatalmaMouseClicked

    private void güncellemeMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_güncellemeMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_güncellemeMouseWheelMoved

    private void güncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncellemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_güncellemeActionPerformed
//veri tablosundaki verileri değiştirilen değerlere göre güncelleyen fonksiyon
    private void güncellemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_güncellemeMouseClicked
        int result=JOptionPane.showConfirmDialog(this, "güncelleme işlemini yapmayı istiyormusunuz");
       if(result==JOptionPane.YES_OPTION){
            if(malzemeid.getText().isEmpty()||miktar.getText().isEmpty()||kar.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Eksik bilgi");
        }else{
            try {
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
                int id = Integer.parseInt(malzemeid.getText());
                String sorgu = "UPDATE yenistok SET Miktar='" + miktar.getText() + "', kar='" + kar.getText() + "' WHERE Id=" + malzemeid.getText();
                Statement add=conn.createStatement();
                add.executeUpdate(sorgu);
                Statement işlem = conn.createStatement();
                ResultSet rs = işlem.executeQuery("SELECT * FROM stok where Id="+id);
                String selectQuery = "SELECT * FROM yenistok WHERE Id=?";
                PreparedStatement selectStatement = conn.prepareStatement(selectQuery);
                selectStatement.setInt(1, id);
       
        if (rs.next()) {
            double eskiFiyat = rs.getDouble("Fiyat");
            //double karorani = rs.getInt("kar") / 100.0;
             String text = kar.getText();
             double karorani = Double.parseDouble(text)/100;
            double yeniFiyat = eskiFiyat + (eskiFiyat * karorani);
            String updatePriceQuery = "UPDATE yenistok SET Fiyat=? WHERE Id=?";
            PreparedStatement updatePriceStatement = conn.prepareStatement(updatePriceQuery);
            updatePriceStatement.setDouble(1, yeniFiyat);
            updatePriceStatement.setInt(2, id);
            updatePriceStatement.executeUpdate();
        }
                
                JOptionPane.showMessageDialog(this, "Başarıyla güncellendi");
                Selectional();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
       }
    }//GEN-LAST:event_güncellemeMouseClicked
//arayüzdeki tabloda bulunan verilerden tıklanılanın verinin bilgilerini textboxlara yazan fonksiyon
    private void TablostokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablostokMouseClicked
        DefaultTableModel model=(DefaultTableModel) Tablostok.getModel();
        int index=Tablostok.getSelectedRow();
        malzemeid.setText(model.getValueAt(index, 0).toString());
        miktar.setText(model.getValueAt(index, 3).toString());
        kar.setText(model.getValueAt(index, 4).toString());
        
    }//GEN-LAST:event_TablostokMouseClicked
//seçim ekranına götüren fonksiyon
    private void anasayfaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anasayfaMouseClicked
        SECIM seçimEkranı = new SECIM();
        seçimEkranı.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anasayfaMouseClicked
//yeni stok adlı veri tablosundaki verileri id numarasına göre silen fonksiyon
    private void çıkarmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_çıkarmaMouseClicked
        int result=JOptionPane.showConfirmDialog(this, "Stok tablosundan silinsin mi?");
       if(result==JOptionPane.YES_OPTION){
            if(malzemeid.getText().isEmpty()){
            JOptionPane.showConfirmDialog(this, "Eksik bilgi ");
        }else{
            try {
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
                String id=malzemeid.getText();
                String sorgu="delete from yenistok where Id= "+id;
                Statement add=conn.createStatement();
                add.executeUpdate(sorgu);
                Selectional();
                JOptionPane.showMessageDialog(this, "Başarılı bir şekilde kaldırıldı");
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
       }
    }//GEN-LAST:event_çıkarmaMouseClicked
//sayfayı kapatan fonksiyon
    private void KapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KapatMouseClicked
//stok sorgusu yapan arayüze giden fonksiyon
    private void fiyatalma1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiyatalma1MouseClicked
        Stokmalzemesorgu seçimEkranı = new Stokmalzemesorgu();
            seçimEkranı.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_fiyatalma1MouseClicked
//yeni stok adlı veri tablosundaki tüm verileri silen fonksiyon
    private void fiyatalma2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiyatalma2MouseClicked
        int result=JOptionPane.showConfirmDialog(this, "Tabloyu silme işlemini gerçekleştirmek istiyormusunuz");
        if(result==JOptionPane.YES_OPTION){
            try {
                    conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
                    Statement stmt = conn.createStatement();
                    String sql = "DELETE FROM yenistok"; // Veritabanındaki tüm verileri silen SQL sorgusu
                    stmt.executeUpdate(sql);
                    stmt.close();
                    conn.close();
                    Selectional();
                    JOptionPane.showMessageDialog(this, "İşsleminiz başarıyla gerçekleştirilmiştir");
                    
                    
                    
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Veritabanı sorgusunda bir sorunla karşılaşıldı");
                }
        }
    }//GEN-LAST:event_fiyatalma2MouseClicked
//yeni stok adlı veri tablosundaki tüm verileri pdf oluşturmak için gertiren fonksiyon
    private String[][] getMaterialDetails(String projectId) throws SQLException {
    List<String[]> materials = new ArrayList<>();
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
        String sql = "SELECT * FROM yenistok";
        pstmt = conn.prepareStatement(sql);
        
        rs = pstmt.executeQuery();

        while (rs.next()) {
            materials.add(new String[]{
                    rs.getString("Id"),
                    rs.getString("Ad"),
                    rs.getString("Cins"),
                    rs.getString("Miktar"),
                    
                    rs.getString("Fiyat")
            });
        }
    } finally {
        if (rs != null) rs.close();
        if (pstmt != null) pstmt.close();
        if (conn != null) conn.close();
    }
    return materials.toArray(new String[0][]);
}
//pdf oluşturan fonksiyon
private void createPDF( String[][] materials) throws FileNotFoundException, DocumentException, SQLException {
    
    Document document = new Document();
    
    PdfWriter.getInstance(document, new FileOutputStream("Teklif.pdf"));

    document.open();
    document.add(new Paragraph("                                                 Prokont yapi ve mimarlik ltd.sti"));
    document.add(new Paragraph(" "));
    document.add(new Paragraph("Bu bir tekliftir  "));
    
   
   
    document.add(new Paragraph(" "));
    // Malzeme Tablosu
    document.add(new Paragraph(" Malzemeler:"));
    document.add(new Paragraph(" "));
    
    PdfPTable table = new PdfPTable(5);
    table.setWidthPercentage(100);
    table.addCell("Malzeme ID");
    table.addCell("Malzeme adı");
    table.addCell("Birim cinsi");
    table.addCell("Birim miktarı");
    
    table.addCell("Birim fiyatı");
    
    
    for (String[] material : materials) {
        for (String data : material) {
            table.addCell(data);
            
            
        }
    }

    document.add(table);
    double totalFiyat = getTotalPrice();
    document.add(new Paragraph(" "));
    document.add(new Paragraph("Toplam Fiyat: " + String.format("%.2f", totalFiyat)));
    document.close();
    
    
}
//yeni stok adlı veri tablosundaki tüm verilerin malzeme adedi ile birim fiyatını çarpıp toplam değeri getiren fonksiyon
private double getTotalPrice() throws SQLException {
    double totalPrice = 0;
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    try {
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/oto", "root", "S19b310?");
        String sql = "SELECT SUM(Miktar * Fiyat) AS ToplamFiyat FROM yenistok ";
        pstmt = conn.prepareStatement(sql);
        rs = pstmt.executeQuery();
        if (rs.next()) {
            totalPrice = rs.getDouble("ToplamFiyat");
        }
    } finally {
        if (rs != null) rs.close();
        if (pstmt != null) pstmt.close();
        if (conn != null) conn.close();
    }
    return totalPrice;
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIYATALMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIYATALMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIYATALMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIYATALMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIYATALMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kapat;
    private javax.swing.JTable Tablostok;
    private javax.swing.JButton anasayfa;
    private javax.swing.JButton ekleme;
    private javax.swing.JButton fiyatalma;
    private javax.swing.JButton fiyatalma1;
    private javax.swing.JButton fiyatalma2;
    private javax.swing.JButton güncelleme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kar;
    private javax.swing.JTextField malzemeid;
    private javax.swing.JTextField miktar;
    private javax.swing.JScrollPane tablostok;
    private javax.swing.JButton temizleme;
    private javax.swing.JButton çıkarma;
    // End of variables declaration//GEN-END:variables
}
